### Crear programador
POST http://localhost:8081/api/programadores
Content-Type: application/json

{
  "nombre": "Juan",
  "email": "juan@example.com",
  "capacidadHoras": 40,
  "rolId": 1
}

### Buscar por nombre
GET http://localhost:8081/api/programadores?nombre=Juan

### Buscar programadores por rol
GET http://localhost:8081/api/programadores/rol/1

### Buscar programador por id
GET http://localhost:8081/api/programadores/1

###Crear tarea
POST http://localhost:8081/api/tareas
Content-Type: application/json

{
"titulo": "Tarea 1",
"descripcion": "Descripcion",
"storyPoints": 5,
"prioridadId": 2,
"estadoId": 1,
"programadorId": 1,
"estimacionHoras": 3,
"horasInvertidas": 0
}


### Buscar tarea por id
GET http://localhost:8081/api/tareas/1

### Listar todas las tareas
GET http://localhost:8081/api/tareas


### Listar tareas del Sprint 1 (Entregable fran 27/11/25)
GET http://localhost:8081/api/tareas/sprint/1
Accept: application/json



