# Generated by Django 5.2.7 on 2025-10-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('P', 'Pop'), ('R', 'Rap'), ('RE', 'Reggeton'), ('E', 'Electronica')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ano_lanzamiento', models.IntegerField(blank=True, null=True)),
                ('duracion', models.IntegerField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='radioapp.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Podcats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('tematica', models.CharField(choices=[('T', 'TERROR'), ('I', 'INVESTIGACION'), ('A', 'ACTUALIDAD')], max_length=20)),
                ('autores', models.ManyToManyField(related_name='podcats', to='radioapp.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Reproducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateField(auto_now_add=True)),
                ('cancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radioapp.cancion')),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radioapp.podcats')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('ciudad', models.CharField(choices=[('CIU', 'CIUDAD REAL'), ('ARG', 'ARGAMASILLA'), ('PU', 'PUERTOLLANO'), ('ALM', 'ALMODOVAR')])),
                ('preferida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='radioapp.usuario')),
            ],
        ),
    ]
