# Generated by Django 5.2.7 on 2025-10-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podcats',
            new_name='Podcast',
        ),
        migrations.RenameModel(
            old_name='Reproducciones',
            new_name='Reproduccion',
        ),
    ]
