# Generated by Django 5.2.7 on 2025-10-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0002_alter_usuario_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cancion',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='radioapp.autor'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='preferida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='radioapp.usuario'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Podcats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('tematica', models.CharField(choices=[('T', 'TERROR'), ('I', 'INVESTIGACION'), ('A', 'ACTUALIDAD')], max_length=20)),
                ('autores', models.ManyToManyField(related_name='podcats', to='radioapp.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Reproducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateField(auto_now_add=True)),
                ('cancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radioapp.cancion')),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radioapp.podcats')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.usuario')),
            ],
        ),
    ]
