# Generated by Django 5.2.7 on 2025-10-13 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0002_rename_podcats_podcast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='preferida',
        ),
        migrations.AddField(
            model_name='usuario',
            name='preferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_preferido', to='radioapp.direccion'),
        ),
    ]
