# Generated by Django 5.2.7 on 2025-10-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0003_remove_direccion_preferida_usuario_preferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducciones', to='radioapp.usuario'),
        ),
    ]
