# Generated by Django 5.2.7 on 2025-10-21 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0004_alter_reproduccion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='preferida',
        ),
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferida', models.BooleanField(default='false')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.usuario')),
            ],
        ),
    ]
