# Generated by Django 5.2.7 on 2025-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
    ]
