# Generated by Django 5.2.7 on 2025-10-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_tarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador',
            name='tecnologia',
            field=models.CharField(choices=[('P', 'PYTHON'), ('J', 'JAVA'), ('PHP', 'PHP')], default='P'),
        ),
    ]
