# Generated by Django 5.2.7 on 2025-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_programador_tecnologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ManyToManyField(to='scrum.programador'),
        ),
    ]
