# Generated by Django 5.2.7 on 2025-10-06 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0006_remove_tarea_usuario_tarea_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
