# Generated by Django 5.2.7 on 2025-10-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_sprint_tarea_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programador',
            old_name='apellidos',
            new_name='apellido',
        ),
    ]
