# Generated by Django 5.2.7 on 2025-10-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0008_rename_apellidos_programador_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programador',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
